import { Layout } from "@/components/layout";
import { LoadingSpinner } from "@/components/ui/loading-spinner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Calendar, Tag, Wallet } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";

type CouponRequest = {
  id: string;
  communityName?: string;
  managerUserId: string;
  numberOfCoupons: number;
  perCouponValue: number;
  couponTotal: number;
  adminCommission: number;
  totalPayable: number;
  reason: string;
  validUntil: string | Date;
  status: string;
  coupon?: null | {
    code: string;
    status: string;
    remainingUnits: number;
    expiresAt: string | Date;
    activatedAt: string | Date | null;
    sharedAt: string | Date | null;
  };
};

function statusBadge(status: string) {
  const s = status.toUpperCase();
  if (s === "REJECTED") return "bg-red-500/10 text-red-600 border-red-500/20";
  if (s === "PENDING_ADMIN") return "bg-amber-500/10 text-amber-600 border-amber-500/20";
  if (s === "APPROVED_NOT_SHARED") return "bg-blue-500/10 text-blue-600 border-blue-500/20";
  return "bg-muted text-muted-foreground";
}

function toInputDate(d: Date) {
  const iso = d.toISOString();
  return iso.slice(0, 10);
}

async function parseJsonResponse<T>(res: Response): Promise<T> {
  const text = await res.text().catch(() => "");
  const trimmed = text.trim();
  if (!trimmed) throw new Error("Empty server response");
  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    return JSON.parse(trimmed) as T;
  }
  throw new Error(trimmed.slice(0, 200) || "Server returned non-JSON response");
}

export default function ManagerCouponRequest() {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const [numberOfCoupons, setNumberOfCoupons] = useState<number>(10);
  const [perCouponValue, setPerCouponValue] = useState<number>(100);
  const [validUntil, setValidUntil] = useState<string>(() => {
    const d = new Date();
    d.setMonth(d.getMonth() + 1);
    return toInputDate(d);
  });
  const [reason, setReason] = useState<string>("Community promo");

  const couponTotal = numberOfCoupons * perCouponValue;
  const adminCommission = Math.round((couponTotal * 12) / 100);
  const totalPayable = couponTotal + adminCommission;

  const { data: requests = [], isLoading: requestsLoading, isError: requestsError, error: requestsErrorObj } = useQuery<CouponRequest[]>({
    queryKey: ["/api/manager/coupons/requests"],
    queryFn: async () => {
      const res = await fetch("/api/manager/coupons/requests", { credentials: "include" });
      if (!res.ok) {
        const text = await res.text().catch(() => "");
        throw new Error(text?.trim()?.slice(0, 200) || "Failed to fetch requests");
      }
      return await parseJsonResponse<CouponRequest[]>(res);
    },
    staleTime: 10000,
    retry: 0,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  });

  const requestMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch("/api/manager/coupons/request", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({
          numberOfCoupons,
          perCouponValue,
          reason,
          validUntil,
        }),
      });
      if (!res.ok) {
        const text = await res.text().catch(() => "");
        throw new Error(text?.trim()?.slice(0, 200) || "Coupon request failed");
      }
      return await parseJsonResponse<any>(res);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/manager/coupons/requests"] });
      toast({ title: "Coupon request submitted", description: "Pending admin approval." });
    },
    onError: (err: Error) => {
      toast({ title: "Request failed", description: err.message, variant: "destructive" });
    },
  });

  const preview = useMemo(
    () => ({
      couponTotal,
      adminCommission,
      totalPayable,
    }),
    [couponTotal, adminCommission, totalPayable],
  );

  return (
    <Layout>
      <div className="flex flex-col gap-8 max-w-4xl mx-auto pb-12">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">Request Coupons</h1>
          <p className="text-muted-foreground mt-1 text-sm font-medium">
            Submit a coupon request. Your code is generated by admin and becomes usable when they Share.
          </p>
        </div>

        <Card className="border-border/50 shadow-sm">
          <div className="h-1.5 bg-primary" />
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-lg text-slate-800">
              <Tag className="w-5 h-5 text-primary" /> Coupon request form
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label className="font-bold">Number of coupon units</Label>
                <Input
                  type="number"
                  min={1}
                  value={numberOfCoupons}
                  onChange={(e) => setNumberOfCoupons(Math.max(1, Number(e.target.value)))}
                  className="h-11 rounded-xl"
                />
              </div>
              <div className="space-y-2">
                <Label className="font-bold">Per-coupon value (₹)</Label>
                <Input
                  type="number"
                  min={1}
                  value={perCouponValue}
                  onChange={(e) => setPerCouponValue(Math.max(1, Number(e.target.value)))}
                  className="h-11 rounded-xl"
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label className="font-bold flex items-center gap-2">
                <Calendar className="w-4 h-4 text-primary" /> Valid until (max 6 months)
              </Label>
              <Input type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)} className="h-11 rounded-xl" />
            </div>

            <div className="space-y-2">
              <Label className="font-bold">Reason</Label>
              <Textarea value={reason} onChange={(e) => setReason(e.target.value)} className="min-h-[110px]" />
            </div>

            <div className="rounded-xl border border-border/50 bg-muted/10 p-4 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Coupon total</span>
                <span className="font-bold">₹{preview.couponTotal.toLocaleString()}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Admin commission (12%)</span>
                <span className="font-bold">₹{preview.adminCommission.toLocaleString()}</span>
              </div>
              <div className="flex justify-between items-center pt-2 border-t border-border/30">
                <span className="font-bold flex items-center gap-2">
                  <Wallet className="w-4 h-4" /> Total payable (reserved)
                </span>
                <span className="font-black text-primary text-lg">₹{preview.totalPayable.toLocaleString()}</span>
              </div>
            </div>

            <Button
              className="w-full h-12 font-bold text-md mt-2 shadow-md bg-primary hover:bg-primary/90"
              onClick={() => requestMutation.mutate()}
              disabled={requestMutation.isPending}
            >
              {requestMutation.isPending ? "Submitting..." : "Checkout once"}
            </Button>
          </CardContent>
        </Card>

        <Card className="border-border/50 shadow-sm">
          <CardHeader className="pb-4">
            <CardTitle className="text-lg text-slate-800">My Coupon Requests</CardTitle>
            <p className="text-sm text-muted-foreground mt-1">Admin will generate code on Approve and activate on Share.</p>
          </CardHeader>
          <CardContent>
            {requestsLoading ? (
              <div className="py-10 flex items-center justify-center">
                <LoadingSpinner />
              </div>
            ) : requestsError ? (
              <div className="py-10 text-center">
                <p className="text-sm text-destructive font-medium">
                  {requestsErrorObj instanceof Error ? requestsErrorObj.message : "Failed to load requests."}
                </p>
              </div>
            ) : requests.length === 0 ? (
              <div className="py-12 text-center border-2 border-dashed border-slate-200 rounded-lg bg-slate-50">
                <p className="text-slate-500 font-medium">No coupon requests yet.</p>
              </div>
            ) : (
              <div className="space-y-4">
                {requests
                  .slice()
                  .reverse()
                  .map((r) => (
                    <div key={r.id} className="flex flex-col sm:flex-row gap-4 sm:items-start sm:justify-between p-5 border border-slate-200 rounded-xl bg-white shadow-sm">
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <p className="font-bold text-slate-900 text-lg truncate">{r.communityName ?? "Community"}</p>
                          <Badge className={`text-[11px] font-bold capitalize px-2 py-0.5 border ${statusBadge(r.status)}`}>
                            {r.status.toLowerCase().replace(/_/g, " ")}
                          </Badge>
                        </div>
                        <p className="text-xs text-slate-500 mt-1">
                          Units: {r.numberOfCoupons} • Value: ₹{r.perCouponValue} • Total: ₹{r.couponTotal}
                        </p>
                        <p className="text-xs text-slate-400 mt-1">Valid until: {new Date(r.validUntil).toLocaleDateString()}</p>
                        <p className="text-xs text-slate-400 mt-1">Reason: {r.reason}</p>
                        {r.coupon ? (
                          <div className="mt-3">
                            <p className="text-sm font-bold text-primary flex items-center gap-2">
                              <Tag className="w-4 h-4" /> Code: {r.coupon.code}
                            </p>
                            <p className="text-xs text-slate-500 mt-0.5">
                              Coupon status: {r.coupon.status} • Remaining units: {r.coupon.remainingUnits}
                            </p>
                          </div>
                        ) : (
                          <p className="text-xs text-muted-foreground mt-3">No coupon code yet (awaiting admin Approve).</p>
                        )}
                      </div>

                      <div className="text-right">
                        <p className="text-xs text-slate-500">Reserved total</p>
                        <p className="font-black text-primary">₹{r.totalPayable.toLocaleString()}</p>
                      </div>
                    </div>
                  ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}

